# Generated by Django 3.0.5 on 2020-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviseApp', '0002_usermodel_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
