# Generated by Django 3.0.5 on 2020-04-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Record',
        ),
    ]
